/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Crash */

#ifndef _Included_Crash
#define _Included_Crash
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Crash
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Crash_printHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
